data:
  dataset: 'dotah_ffa_net' # TODO: insert dataset name here

train:
  batch_size: 64
  lr: 0.0001
  n_epochs: 5
  num_workers: 4 # change this based on number of cores on your CPU. 4 is sufficient for 1 gpu. If unsure leave at 1.

network:
  model: 'ffa_net'

optimizer:
  type: "adamw" # adamw or sgd
  weight_decay: 0.0 #0.001