data:
  dataset: kjrd # TODO: insert dataset name here

train:
  batch_size: 4
  lr: 0.0001
  n_epochs: 12
  num_workers: 4 # change this based on number of cores on your CPU. 4 is sufficient for 1 gpu. If unsure leave at 1.
  use_diffusion: False

network:
  model: 'kjrd_net' #  use name 'kjrd_net_diffusion' is use_diffusion paramter is set to True

# optimizer:
#   type: "adamw" # adamw or sgd
#   weight_decay: 0.0 #0.001

loss:
  lmbda: 2 #do not rename to lambda as it is a reserved keyword